/*
 * botcast API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`episodes_episode_id_delete`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum EpisodesEpisodeIdDeleteError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`episodes_episode_id_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum EpisodesEpisodeIdGetError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`episodes_episode_id_put`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum EpisodesEpisodeIdPutError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`episodes_post`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum EpisodesPostError {
    UnknownValue(serde_json::Value),
}


pub async fn episodes_episode_id_delete(configuration: &configuration::Configuration, episode_id: &str) -> Result<(), Error<EpisodesEpisodeIdDeleteError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_episode_id = episode_id;

    let uri_str = format!("{}/episodes/{episodeId}", configuration.base_path, episodeId=crate::apis::urlencode(p_episode_id));
    let mut req_builder = configuration.client.request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<EpisodesEpisodeIdDeleteError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn episodes_episode_id_get(configuration: &configuration::Configuration, episode_id: &str) -> Result<models::Episode, Error<EpisodesEpisodeIdGetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_episode_id = episode_id;

    let uri_str = format!("{}/episodes/{episodeId}", configuration.base_path, episodeId=crate::apis::urlencode(p_episode_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::Episode`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::Episode`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<EpisodesEpisodeIdGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn episodes_episode_id_put(configuration: &configuration::Configuration, episode_id: &str, episodes_episode_id_put_request: models::EpisodesEpisodeIdPutRequest) -> Result<(), Error<EpisodesEpisodeIdPutError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_episode_id = episode_id;
    let p_episodes_episode_id_put_request = episodes_episode_id_put_request;

    let uri_str = format!("{}/episodes/{episodeId}", configuration.base_path, episodeId=crate::apis::urlencode(p_episode_id));
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_episodes_episode_id_put_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<EpisodesEpisodeIdPutError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn episodes_post(configuration: &configuration::Configuration, episodes_post_request: models::EpisodesPostRequest) -> Result<(), Error<EpisodesPostError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_episodes_post_request = episodes_post_request;

    let uri_str = format!("{}/episodes", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_episodes_post_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<EpisodesPostError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

