/*
 * botcast API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`corners_corner_id_mails_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CornersCornerIdMailsGetError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`corners_corner_id_mails_mail_id_delete`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CornersCornerIdMailsMailIdDeleteError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`corners_corner_id_mails_post`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CornersCornerIdMailsPostError {
    UnknownValue(serde_json::Value),
}


pub async fn corners_corner_id_mails_get(configuration: &configuration::Configuration, corner_id: &str) -> Result<Vec<models::Mail>, Error<CornersCornerIdMailsGetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_corner_id = corner_id;

    let uri_str = format!("{}/corners/{cornerId}/mails", configuration.base_path, cornerId=crate::apis::urlencode(p_corner_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::Mail&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::Mail&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CornersCornerIdMailsGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn corners_corner_id_mails_mail_id_delete(configuration: &configuration::Configuration, corner_id: &str, mail_id: &str) -> Result<(), Error<CornersCornerIdMailsMailIdDeleteError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_corner_id = corner_id;
    let p_mail_id = mail_id;

    let uri_str = format!("{}/corners/{cornerId}/mails/{mailId}", configuration.base_path, cornerId=crate::apis::urlencode(p_corner_id), mailId=crate::apis::urlencode(p_mail_id));
    let mut req_builder = configuration.client.request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<CornersCornerIdMailsMailIdDeleteError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn corners_corner_id_mails_post(configuration: &configuration::Configuration, corner_id: &str, corners_corner_id_mails_post_request: models::CornersCornerIdMailsPostRequest) -> Result<(), Error<CornersCornerIdMailsPostError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_corner_id = corner_id;
    let p_corners_corner_id_mails_post_request = corners_corner_id_mails_post_request;

    let uri_str = format!("{}/corners/{cornerId}/mails", configuration.base_path, cornerId=crate::apis::urlencode(p_corner_id));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_corners_corner_id_mails_post_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<CornersCornerIdMailsPostError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

