/*
 * botcast API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum Section {
    SerifSection(Box<models::SerifSection>),
    AudioSection(Box<models::AudioSection>),
}

impl Default for Section {
    fn default() -> Self {
        Self::SerifSection(Default::default())
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "Serif")]
    Serif,
    #[serde(rename = "Audio")]
    Audio,
}

impl Default for Type {
    fn default() -> Type {
        Self::Serif
    }
}

