
@endpoint = http://localhost:8000
@voicevox = http://127.0.0.1:50021

###
GET {{endpoint}}/api/v1/feeds
Content-Type: application/json; charset=UTF-8

###
GET {{endpoint}}/api/v1/feeds/4edd754ca51e5940bb4c61b952feabf0a1848610d07617ff50a3d22ba80439c2
Content-Type: application/json; charset=UTF-8

###
POST {{endpoint}}/api/v1/feeds
Content-Type: application/json; charset=UTF-8

{
  "title": "比翼の鳥",
  "sources": [
    {
      "url": "https://gist.githubusercontent.com/wakame-tech/5aa99e1d3e6253dde5405f4e8e662e8d/raw/8d9dd19fcba455afb7f3cffd1979a0f118c7b6ae/hyokass_19669327.txt"
    }
  ]
}

###
GET {{voicevox}}/user_dict