/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/t/{tenantId}/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Run record writes atomically: either every operation is applied or none is.
         *     Fails with 400 (validation), 403 (write not allowed), 404 (missing record),
         *     409 (unique constraint) or 412 (version mismatch). */
        post: operations["BatchApi_execute"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/t/{tenantId}/canvas/edges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["CanvasApi_listEdges"];
        put?: never;
        post: operations["CanvasApi_createEdge"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/t/{tenantId}/canvas/edges/{edgeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["CanvasApi_deleteEdge"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/t/{tenantId}/canvas/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["CanvasApi_query"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/t/{tenantId}/collections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["CollectionApi_list"];
        put?: never;
        post: operations["CollectionApi_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/t/{tenantId}/collections/{collectionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["CollectionApi_read"];
        put: operations["CollectionApi_update"];
        post?: never;
        delete: operations["CollectionApi_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/t/{tenantId}/records/{collectionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["RecordApi_list"];
        put?: never;
        post: operations["RecordApi_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/t/{tenantId}/records/{collectionId}/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["RecordApi_generate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/t/{tenantId}/records/{collectionId}/merge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["RecordApi_mergeRecords"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/t/{tenantId}/records/{collectionId}/with-relations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["RecordApi_listWithRelations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/t/{tenantId}/records/{collectionId}/{recordId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["RecordApi_read"];
        put: operations["RecordApi_update"];
        post?: never;
        delete: operations["RecordApi_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/t/{tenantId}/records/{collectionId}/{recordId}/copy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["RecordApi_copyRecord"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/t/{tenantId}/records/{collectionId}/{recordId}/images/{fieldName}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["RecordApi_getImage"];
        put?: never;
        post: operations["RecordApi_uploadImage"];
        delete: operations["RecordApi_deleteImage"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/t/{tenantId}/records/{collectionId}/{recordId}/referenced-by": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List the records referencing this record through their `data` fields */
        get: operations["RecordApi_referencedBy"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/t/{tenantId}/records/{collectionId}/{recordId}/split": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["RecordApi_splitRecord"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/t/{tenantId}/scripts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ScriptApi_execute"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        BatchOperation: {
            /** @enum {string} */
            op: "create" | "update" | "delete";
            collection_id: string;
            /** @description Required for update / delete */
            record_id?: string;
            /** @description Required for create / update. Validated against the collection schema */
            data?: Record<string, never>;
            /**
             * Format: int64
             * @description Optimistic lock for update / delete. The whole batch fails (412) if the record has another version
             */
            expected_version?: number;
        };
        BatchRequest: {
            operations: components["schemas"]["BatchOperation"][];
        };
        BatchResponse: {
            /** @description One entry per operation, in order */
            results: components["schemas"]["BatchResult"][];
        };
        BatchResult: {
            /** @description The written record for create / update, null for delete */
            record: components["schemas"]["Record_"] | null;
        };
        CanvasQueryRequest: {
            /** @description Starting record ID in "table:id" format */
            record_id: string;
            /** @description Graph traversal depth (default: 1) */
            depth?: number;
            /** @description Filter conditions on record fields */
            conditions?: Record<string, never>;
            /**
             * @description Export format
             * @enum {string}
             */
            format: "json-canvas" | "markdown";
        };
        CanvasQueryResponse: {
            /** @enum {string} */
            format: "json-canvas" | "markdown";
            json_canvas?: components["schemas"]["JsonCanvasResponse"];
            markdown?: string;
        };
        Collection: {
            readonly id: string;
            name: string;
            schema: Record<string, never>;
            access?: components["schemas"]["CollectionAccess"];
            readonly created_at: string;
        };
        /** @description Per-collection access policy. Defaults keep pre-existing behaviour. */
        CollectionAccess: {
            /**
             * @description "public" = any authenticated user can read, "owner" = only the record owner
             * @enum {string}
             */
            read: "public" | "owner";
            /**
             * @description "authenticated" = any authenticated user can write, "owner" = owner or a user listed in writers_field
             * @enum {string}
             */
            write: "authenticated" | "owner";
            /** @description Name of a `data` field holding an array of additionally-allowed writer IDs */
            writers_field?: string;
        };
        CopyRecordRequest: {
            /** @description Target collection ID to copy the record to */
            target_collection_id: string;
        };
        CreateEdgeRequest: {
            from: string;
            to: string;
            label: string;
        };
        CreateOrUpdateCollection: {
            name: string;
            schema: Record<string, never>;
            access?: components["schemas"]["CollectionAccess"];
        };
        CreateOrUpdateRecord_: {
            data: Record<string, never>;
        };
        Edge: {
            readonly id: string;
            /** @description Source record ID in "table:id" format */
            from: string;
            /** @description Target record ID in "table:id" format */
            to: string;
            /** @description Edge label (e.g. "belongs_to", "related_to") */
            label: string;
            readonly created_at: string;
        };
        ExecuteScriptRequest: {
            /** @enum {string} */
            language: "python3" | "nodejs";
            code: string;
            preload?: string;
            enable_network?: boolean;
        };
        ExecuteScriptResponse: {
            code: number;
            message: "success" | string;
            data: {
                stdout: string;
                error: string;
            };
        };
        /** @description 403: authenticated, but not allowed to perform the operation (e.g. writing someone else's record). Do not sign out. */
        ForbiddenError: {
            /** @enum {string} */
            code: "FORBIDDEN";
            message: string;
        };
        GenerateRecordRequest: {
            prompt: string;
        };
        GetImageResponse: {
            /** @description Base64 encoded image data */
            data: string;
            /** @description MIME type */
            content_type: string;
            /** @description File size in bytes */
            size: number;
        };
        ImageField: {
            /** @description File pointer (e.g. "images:/collection_id/record_id/field_name") */
            pointer: string;
            /** @description MIME type (e.g. "image/png", "image/jpeg") */
            content_type: string;
            /** @description File size in bytes */
            size: number;
            /** @description Image URL */
            url: string;
        };
        JsonCanvasEdge: {
            id: string;
            fromNode: string;
            toNode: string;
            label?: string;
        };
        JsonCanvasNode: {
            id: string;
            x: number;
            y: number;
            width: number;
            height: number;
            /** @enum {string} */
            type: "text";
            text: string;
        };
        JsonCanvasResponse: {
            nodes: components["schemas"]["JsonCanvasNode"][];
            edges: components["schemas"]["JsonCanvasEdge"][];
        };
        MergeRecordsRequest: {
            /** @description Record IDs to merge (first one becomes the target) */
            source_record_ids: string[];
            /** @description Target record ID (must be in source_record_ids) */
            target_record_id: string;
            /** @description Field names to add (numeric values will be summed) */
            add_fields?: string[];
            /** @description Whether to delete source records after merge (default: false) */
            delete_sources?: boolean;
        };
        NotFoundError: {
            /** @enum {string} */
            code: "NOT_FOUND";
            message: string;
        };
        RecordWithRelations: {
            id: string;
            data: Record<string, never>;
            owner_id: string | null;
            created_at: string | null;
            updated_at: string | null;
            /**
             * Format: int64
             * @description Same as `Record_.version`; pass it back as `If-Match` for optimistic locking
             */
            version: number;
            relations: components["schemas"]["RelatedRecord"][];
        };
        Record_: {
            readonly id: string;
            data: Record<string, never>;
            /** @description Record owner's user ID, taken from the JWT subject at creation time */
            readonly owner_id: string | null;
            readonly created_at: string | null;
            readonly updated_at: string | null;
            /**
             * Format: int64
             * @description Monotonically increasing version, starting at 1 and incremented on every update.
             *     Pass it back as `If-Match` (update / delete) or `expected_version` (batch) for optimistic locking.
             */
            readonly version: number;
        };
        ReferencedByResponse: {
            items: components["schemas"]["ReferencingRecord"][];
        };
        ReferencingRecord: {
            /** @description Collection ID the referencing record belongs to */
            collection_id: string;
            /** @description Field path holding the reference (e.g. "user_id", "members[0].user_id") */
            field: string;
            record: components["schemas"]["Record_"];
        };
        RelatedRecord: {
            /** @description Edge ID connecting the two records */
            edge_id: string;
            /** @description Edge label */
            label: string;
            /**
             * @description Edge direction seen from the record holding this relation
             * @enum {string}
             */
            direction: "outgoing" | "incoming";
            record: components["schemas"]["Record_"];
        };
        SplitRecordRequest: {
            /** @description Split specifications: each object contains field names and values to subtract */
            splits: Record<string, never>[];
        };
        SplitRecordResponse: {
            /** @description Original record after split (with subtracted values) */
            original: components["schemas"]["Record_"];
            /** @description New records created from splits */
            splits: components["schemas"]["Record_"][];
        };
        /** @description 401: the token is missing, invalid or expired. Sign in again. */
        UnauthorizedError: {
            /** @enum {string} */
            code: "UNAUTHORIZED";
            message: string;
        };
        UpdateCollection: {
            name: string;
            access?: components["schemas"]["CollectionAccess"];
        };
        UploadImageRequest: {
            /** @description Base64 encoded file data (image, audio or subtitle text) */
            data: string;
            /**
             * @description MIME type
             * @enum {string}
             */
            content_type: "image/png" | "image/jpeg" | "image/webp" | "image/gif" | "audio/mpeg" | "audio/wav" | "text/plain";
            /** @description Optional filename */
            filename?: string;
        };
        UploadImageResponse: {
            /** @description Saved file pointer */
            pointer: string;
            /** @description Image URL */
            url: string;
        };
        ValidationError: {
            /** @enum {string} */
            code: "VALIDATION_ERROR";
            message: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    BatchApi_execute: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchResponse"];
                };
            };
        };
    };
    CanvasApi_listEdges: {
        parameters: {
            query: {
                record_id: string;
            };
            header?: never;
            path: {
                tenantId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Edge"][];
                };
            };
        };
    };
    CanvasApi_createEdge: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEdgeRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Edge"];
                };
            };
        };
    };
    CanvasApi_deleteEdge: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: string;
                edgeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description There is no content to send for this request, but the headers may be useful.  */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CanvasApi_query: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CanvasQueryRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CanvasQueryResponse"];
                };
            };
        };
    };
    CollectionApi_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Collection"][];
                };
            };
        };
    };
    CollectionApi_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrUpdateCollection"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Collection"];
                };
            };
        };
    };
    CollectionApi_read: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: string;
                collectionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Collection"];
                };
            };
        };
    };
    CollectionApi_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: string;
                collectionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCollection"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Collection"];
                };
            };
        };
    };
    CollectionApi_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: string;
                collectionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description There is no content to send for this request, but the headers may be useful.  */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RecordApi_list: {
        parameters: {
            query?: {
                /** @description Filter conditions in `<field>:<op>:<value>` form, AND-combined. Ops: `eq`, `contains` */
                filter?: string[];
                /** @description Field name to sort by */
                sort?: string;
                /** @description Sort direction (default: asc) */
                order?: "asc" | "desc";
                /** @description Maximum number of records to return */
                limit?: number;
                /** @description Number of records to skip */
                offset?: number;
            };
            header?: never;
            path: {
                tenantId: string;
                collectionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Record_"][];
                };
            };
        };
    };
    RecordApi_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: string;
                collectionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrUpdateRecord_"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Record_"];
                };
            };
        };
    };
    RecordApi_generate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: string;
                collectionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateRecordRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Record_"];
                };
            };
        };
    };
    RecordApi_mergeRecords: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: string;
                collectionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MergeRecordsRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Record_"];
                };
            };
        };
    };
    RecordApi_listWithRelations: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: string;
                collectionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordWithRelations"][];
                };
            };
        };
    };
    RecordApi_read: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: string;
                collectionId: string;
                recordId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Record_"];
                };
            };
        };
    };
    RecordApi_update: {
        parameters: {
            query?: never;
            header?: {
                /** @description Expected `version`. If the record has a different version, nothing is written (412) */
                "If-Match"?: string;
            };
            path: {
                tenantId: string;
                collectionId: string;
                recordId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrUpdateRecord_"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Record_"];
                };
            };
        };
    };
    RecordApi_delete: {
        parameters: {
            query?: never;
            header?: {
                /** @description Expected `version`. If the record has a different version, nothing is deleted (412) */
                "If-Match"?: string;
            };
            path: {
                tenantId: string;
                collectionId: string;
                recordId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description There is no content to send for this request, but the headers may be useful.  */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RecordApi_copyRecord: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: string;
                collectionId: string;
                recordId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CopyRecordRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Record_"];
                };
            };
        };
    };
    RecordApi_getImage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: string;
                collectionId: string;
                recordId: string;
                fieldName: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": unknown;
                };
            };
        };
    };
    RecordApi_uploadImage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: string;
                collectionId: string;
                recordId: string;
                fieldName: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UploadImageRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadImageResponse"];
                };
            };
        };
    };
    RecordApi_deleteImage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: string;
                collectionId: string;
                recordId: string;
                fieldName: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description There is no content to send for this request, but the headers may be useful.  */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RecordApi_referencedBy: {
        parameters: {
            query?: {
                /** @description Restrict the search to a single collection */
                collection_id?: string;
                /** @description Restrict the results to a single field path */
                field?: string;
            };
            header?: never;
            path: {
                tenantId: string;
                collectionId: string;
                recordId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReferencedByResponse"];
                };
            };
        };
    };
    RecordApi_splitRecord: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: string;
                collectionId: string;
                recordId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SplitRecordRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SplitRecordResponse"];
                };
            };
        };
    };
    ScriptApi_execute: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExecuteScriptRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExecuteScriptResponse"];
                };
            };
        };
    };
}
