/*
 * botcast API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CornersCornerIdMailsPostRequest {
    #[serde(rename = "body")]
    pub body: std::collections::HashMap<String, serde_json::Value>,
}

impl CornersCornerIdMailsPostRequest {
    pub fn new(body: std::collections::HashMap<String, serde_json::Value>) -> CornersCornerIdMailsPostRequest {
        CornersCornerIdMailsPostRequest {
            body,
        }
    }
}

