/*
 * botcast API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CornersCornerIdPostRequest {
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "mail_schema", skip_serializing_if = "Option::is_none")]
    pub mail_schema: Option<std::collections::HashMap<String, serde_json::Value>>,
}

impl CornersCornerIdPostRequest {
    pub fn new(title: String, description: String) -> CornersCornerIdPostRequest {
        CornersCornerIdPostRequest {
            title,
            description,
            mail_schema: None,
        }
    }
}

