/*
 * botcast API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MailsMailIdPostRequest {
    #[serde(rename = "corner_id")]
    pub corner_id: uuid::Uuid,
    #[serde(rename = "body")]
    pub body: std::collections::HashMap<String, serde_json::Value>,
}

impl MailsMailIdPostRequest {
    pub fn new(corner_id: uuid::Uuid, body: std::collections::HashMap<String, serde_json::Value>) -> MailsMailIdPostRequest {
        MailsMailIdPostRequest {
            corner_id,
            body,
        }
    }
}

