/*
 * botcast API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ScriptsScriptIdPutRequest {
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "template")]
    pub template: std::collections::HashMap<String, serde_json::Value>,
}

impl ScriptsScriptIdPutRequest {
    pub fn new(title: String, description: String, template: std::collections::HashMap<String, serde_json::Value>) -> ScriptsScriptIdPutRequest {
        ScriptsScriptIdPutRequest {
            title,
            description,
            template,
        }
    }
}

