/*
 * botcast API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SecretsPostRequestNewsInner {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "value")]
    pub value: String,
}

impl SecretsPostRequestNewsInner {
    pub fn new(name: String, value: String) -> SecretsPostRequestNewsInner {
        SecretsPostRequestNewsInner {
            name,
            value,
        }
    }
}

