/*
 * botcast API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TasksPostRequest {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "args")]
    pub args: std::collections::HashMap<String, serde_json::Value>,
    #[serde(rename = "cron", skip_serializing_if = "Option::is_none")]
    pub cron: Option<String>,
}

impl TasksPostRequest {
    pub fn new(id: uuid::Uuid, args: std::collections::HashMap<String, serde_json::Value>) -> TasksPostRequest {
        TasksPostRequest {
            id,
            args,
            cron: None,
        }
    }
}

