/*
 * botcast API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TasksTaskIdPutRequest {
    #[serde(rename = "status")]
    pub status: models::TaskStatus,
    #[serde(rename = "args")]
    pub args: std::collections::HashMap<String, serde_json::Value>,
}

impl TasksTaskIdPutRequest {
    pub fn new(status: models::TaskStatus, args: std::collections::HashMap<String, serde_json::Value>) -> TasksTaskIdPutRequest {
        TasksTaskIdPutRequest {
            status,
            args,
        }
    }
}

