/*
 * botcast API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Podcast {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "icon")]
    pub icon: String,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "user")]
    pub user: Box<models::User>,
}

impl Podcast {
    pub fn new(id: uuid::Uuid, title: String, icon: String, created_at: String, description: String, user: models::User) -> Podcast {
        Podcast {
            id,
            title,
            icon,
            created_at,
            description,
            user: Box::new(user),
        }
    }
}

