/*
 * botcast API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Script {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "template")]
    pub template: std::collections::HashMap<String, serde_json::Value>,
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "arguments")]
    pub arguments: std::collections::HashMap<String, serde_json::Value>,
}

impl Script {
    pub fn new(id: uuid::Uuid, template: std::collections::HashMap<String, serde_json::Value>, title: String, description: String, arguments: std::collections::HashMap<String, serde_json::Value>) -> Script {
        Script {
            id,
            template,
            title,
            description,
            arguments,
        }
    }
}

