/*
 * botcast API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SerifSection {
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "speaker")]
    pub speaker: String,
    #[serde(rename = "text")]
    pub text: String,
}

impl SerifSection {
    pub fn new(r#type: Type, speaker: String, text: String) -> SerifSection {
        SerifSection {
            r#type,
            speaker,
            text,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "Serif")]
    Serif,
}

impl Default for Type {
    fn default() -> Type {
        Self::Serif
    }
}

