/*
 * botcast API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SignUpResponse {
    #[serde(rename = "accessToken")]
    pub access_token: String,
}

impl SignUpResponse {
    pub fn new(access_token: String) -> SignUpResponse {
        SignUpResponse {
            access_token,
        }
    }
}

