openapi: '3.1.1'
info:
  title: botcast API
  version: '1.0'
servers:
  - url: http://localhost:1234
paths:
  /signUp:
    post:
      tags:
        - Auth
      summary: Sign up
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
              required:
                - email
                - password
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                required:
                  - accessToken
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '409':
          description: Conflict
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /signIn:
    post:
      tags:
        - Auth
      summary: Sign in
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
              required:
                - email
                - password
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                required:
                  - accessToken
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /me:
    get:
      tags:
        - Auth
      security:
        - Bearer: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
components:
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
        auth_id:
          type: string
          format: uuid
        email:
          type: string
          format: email
        name:
          type: string
      required:
        - id
        - auth_id
        - email
        - name
    SerifSection:
      type: object
      properties:
        type:
          type: string
          enum:
            - Serif
        speaker:
          type: string
        text:
          type: string
      required:
        - type
        - speaker
        - text
    AudioSection:
      type: object
      properties:
        type:
          type: string
          enum:
            - Audio
        url:
          type: string
        from:
          type: number
        to:
          type: number
      required:
        - type
        - url
    Section:
      type: object
      oneOf:
        - $ref: '#/components/schemas/SerifSection'
        - $ref: '#/components/schemas/AudioSection'
