openapi: '3.1.1'
info:
  title: botcast API
  version: '1.0'
servers:
  - url: http://localhost:1234
paths:
  /signUp:
    post:
      tags:
        - Auth
      summary: Sign up
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
              required:
                - email
                - password
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                required:
                  - accessToken
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '409':
          description: Conflict
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /signIn:
    post:
      tags:
        - Auth
      summary: Sign in
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
              required:
                - email
                - password
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                required:
                  - accessToken
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /me:
    get:
      tags:
        - Auth
      security:
        - Bearer: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /tasks:
    get:
      tags:
        - Tasks
      security:
        - Bearer: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
    post:
      tags:
        - Tasks
      security:
        - Bearer: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                  format: uuid
                args:
                  type: object
                  additionalProperties: true
                cron:
                  type: string
              required:
                - id
                - args
      responses:
        '200':
          description: OK
  /tasks/{taskId}:
    parameters:
      - in: path
        name: taskId
        schema:
          type: string
          format: uuid
        required: true
    delete:
      tags:
        - Tasks
      security:
        - Bearer: []
      responses:
        '200':
          description: OK
    put:
      tags:
        - Tasks
      security:
        - Bearer: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  $ref: '#/components/schemas/TaskStatus'
                args:
                  type: object
                  additionalProperties: true
              required:
                - status
                - args
      responses:
        '200':
          description: OK
components:
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
        auth_id:
          type: string
          format: uuid
        email:
          type: string
          format: email
        name:
          type: string
      required:
        - id
        - auth_id
        - email
        - name
    SerifSection:
      type: object
      properties:
        type:
          type: string
          enum:
            - Serif
        speaker:
          type: string
        text:
          type: string
      required:
        - type
        - speaker
        - text
    AudioSection:
      type: object
      properties:
        type:
          type: string
          enum:
            - Audio
        url:
          type: string
        from:
          type: number
        to:
          type: number
      required:
        - type
        - url
    Section:
      type: object
      oneOf:
        - $ref: '#/components/schemas/SerifSection'
        - $ref: '#/components/schemas/AudioSection'
    Task:
      type: object
      properties:
        id:
          type: string
          format: uuid
        status:
          $ref: '#/components/schemas/TaskStatus'
        args:
          type: object
          additionalProperties: true
        user_id:
          type: string
          format: uuid
        execute_after:
          type: string
          format: date-time
        executed_at:
          type: string
          format: date-time
        executed_finished_at:
          type: string
          format: date-time
        result:
          type: object
          additionalProperties: true
        cron:
          type: string
      required:
        - id
        - status
        - args
        - execute_after
    TaskStatus:
      type: string
      enum:
        - PENDING
        - RUNNING
        - COMPLETED
        - FAILED
