set dotenv-load := true

run:
    cargo run -p api

gen_server:
    openapi-generator-cli generate -i ../spec/tsp-output/schema/openapi.yaml -g rust-axum -o ./crates/openapi-gen

gen_mcp:
    openapi-mcp-generator --input ../spec/tsp-output/schema/openapi.yaml --base-url http://localhost:3002 --output ../mcp --force