/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScriptsIndexRouteImport } from './routes/scripts/index'

const SigninLazyRouteImport = createFileRoute('/signin')()
const IndexLazyRouteImport = createFileRoute('/')()
const PodcastsIndexLazyRouteImport = createFileRoute('/podcasts/')()
const UsersUserIdLazyRouteImport = createFileRoute('/users/$userId')()
const ScriptsNewLazyRouteImport = createFileRoute('/scripts/new')()
const ScriptsScriptIdLazyRouteImport = createFileRoute('/scripts/$scriptId')()
const PodcastsNewLazyRouteImport = createFileRoute('/podcasts/new')()
const PodcastsPodcastIdLazyRouteImport = createFileRoute(
  '/podcasts/$podcastId',
)()
const ScriptsScriptIdEditLazyRouteImport = createFileRoute(
  '/scripts/$scriptId_/edit',
)()
const PodcastsPodcastIdEditLazyRouteImport = createFileRoute(
  '/podcasts/$podcastId_/edit',
)()
const PodcastsPodcastIdEpisodesEpisodeIdLazyRouteImport = createFileRoute(
  '/podcasts/$podcastId_/episodes/$episodeId',
)()

const SigninLazyRoute = SigninLazyRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/signin.lazy').then((d) => d.Route))
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const PodcastsIndexLazyRoute = PodcastsIndexLazyRouteImport.update({
  id: '/podcasts/',
  path: '/podcasts/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/podcasts/index.lazy').then((d) => d.Route),
)
const ScriptsIndexRoute = ScriptsIndexRouteImport.update({
  id: '/scripts/',
  path: '/scripts/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersUserIdLazyRoute = UsersUserIdLazyRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/users/$userId.lazy').then((d) => d.Route))
const ScriptsNewLazyRoute = ScriptsNewLazyRouteImport.update({
  id: '/scripts/new',
  path: '/scripts/new',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/scripts/new.lazy').then((d) => d.Route))
const ScriptsScriptIdLazyRoute = ScriptsScriptIdLazyRouteImport.update({
  id: '/scripts/$scriptId',
  path: '/scripts/$scriptId',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/scripts/$scriptId.lazy').then((d) => d.Route),
)
const PodcastsNewLazyRoute = PodcastsNewLazyRouteImport.update({
  id: '/podcasts/new',
  path: '/podcasts/new',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/podcasts/new.lazy').then((d) => d.Route))
const PodcastsPodcastIdLazyRoute = PodcastsPodcastIdLazyRouteImport.update({
  id: '/podcasts/$podcastId',
  path: '/podcasts/$podcastId',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/podcasts/$podcastId.lazy').then((d) => d.Route),
)
const ScriptsScriptIdEditLazyRoute = ScriptsScriptIdEditLazyRouteImport.update({
  id: '/scripts/$scriptId_/edit',
  path: '/scripts/$scriptId/edit',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/scripts/$scriptId_/edit.lazy').then((d) => d.Route),
)
const PodcastsPodcastIdEditLazyRoute =
  PodcastsPodcastIdEditLazyRouteImport.update({
    id: '/podcasts/$podcastId_/edit',
    path: '/podcasts/$podcastId/edit',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/podcasts/$podcastId_/edit.lazy').then((d) => d.Route),
  )
const PodcastsPodcastIdEpisodesEpisodeIdLazyRoute =
  PodcastsPodcastIdEpisodesEpisodeIdLazyRouteImport.update({
    id: '/podcasts/$podcastId_/episodes/$episodeId',
    path: '/podcasts/$podcastId/episodes/$episodeId',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/podcasts/$podcastId_/episodes/$episodeId.lazy').then(
      (d) => d.Route,
    ),
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/signin': typeof SigninLazyRoute
  '/podcasts/$podcastId': typeof PodcastsPodcastIdLazyRoute
  '/podcasts/new': typeof PodcastsNewLazyRoute
  '/scripts/$scriptId': typeof ScriptsScriptIdLazyRoute
  '/scripts/new': typeof ScriptsNewLazyRoute
  '/users/$userId': typeof UsersUserIdLazyRoute
  '/scripts/': typeof ScriptsIndexRoute
  '/podcasts/': typeof PodcastsIndexLazyRoute
  '/podcasts/$podcastId/edit': typeof PodcastsPodcastIdEditLazyRoute
  '/scripts/$scriptId/edit': typeof ScriptsScriptIdEditLazyRoute
  '/podcasts/$podcastId/episodes/$episodeId': typeof PodcastsPodcastIdEpisodesEpisodeIdLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/signin': typeof SigninLazyRoute
  '/podcasts/$podcastId': typeof PodcastsPodcastIdLazyRoute
  '/podcasts/new': typeof PodcastsNewLazyRoute
  '/scripts/$scriptId': typeof ScriptsScriptIdLazyRoute
  '/scripts/new': typeof ScriptsNewLazyRoute
  '/users/$userId': typeof UsersUserIdLazyRoute
  '/scripts': typeof ScriptsIndexRoute
  '/podcasts': typeof PodcastsIndexLazyRoute
  '/podcasts/$podcastId/edit': typeof PodcastsPodcastIdEditLazyRoute
  '/scripts/$scriptId/edit': typeof ScriptsScriptIdEditLazyRoute
  '/podcasts/$podcastId/episodes/$episodeId': typeof PodcastsPodcastIdEpisodesEpisodeIdLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/signin': typeof SigninLazyRoute
  '/podcasts/$podcastId': typeof PodcastsPodcastIdLazyRoute
  '/podcasts/new': typeof PodcastsNewLazyRoute
  '/scripts/$scriptId': typeof ScriptsScriptIdLazyRoute
  '/scripts/new': typeof ScriptsNewLazyRoute
  '/users/$userId': typeof UsersUserIdLazyRoute
  '/scripts/': typeof ScriptsIndexRoute
  '/podcasts/': typeof PodcastsIndexLazyRoute
  '/podcasts/$podcastId_/edit': typeof PodcastsPodcastIdEditLazyRoute
  '/scripts/$scriptId_/edit': typeof ScriptsScriptIdEditLazyRoute
  '/podcasts/$podcastId_/episodes/$episodeId': typeof PodcastsPodcastIdEpisodesEpisodeIdLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signin'
    | '/podcasts/$podcastId'
    | '/podcasts/new'
    | '/scripts/$scriptId'
    | '/scripts/new'
    | '/users/$userId'
    | '/scripts/'
    | '/podcasts/'
    | '/podcasts/$podcastId/edit'
    | '/scripts/$scriptId/edit'
    | '/podcasts/$podcastId/episodes/$episodeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signin'
    | '/podcasts/$podcastId'
    | '/podcasts/new'
    | '/scripts/$scriptId'
    | '/scripts/new'
    | '/users/$userId'
    | '/scripts'
    | '/podcasts'
    | '/podcasts/$podcastId/edit'
    | '/scripts/$scriptId/edit'
    | '/podcasts/$podcastId/episodes/$episodeId'
  id:
    | '__root__'
    | '/'
    | '/signin'
    | '/podcasts/$podcastId'
    | '/podcasts/new'
    | '/scripts/$scriptId'
    | '/scripts/new'
    | '/users/$userId'
    | '/scripts/'
    | '/podcasts/'
    | '/podcasts/$podcastId_/edit'
    | '/scripts/$scriptId_/edit'
    | '/podcasts/$podcastId_/episodes/$episodeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  SigninLazyRoute: typeof SigninLazyRoute
  PodcastsPodcastIdLazyRoute: typeof PodcastsPodcastIdLazyRoute
  PodcastsNewLazyRoute: typeof PodcastsNewLazyRoute
  ScriptsScriptIdLazyRoute: typeof ScriptsScriptIdLazyRoute
  ScriptsNewLazyRoute: typeof ScriptsNewLazyRoute
  UsersUserIdLazyRoute: typeof UsersUserIdLazyRoute
  ScriptsIndexRoute: typeof ScriptsIndexRoute
  PodcastsIndexLazyRoute: typeof PodcastsIndexLazyRoute
  PodcastsPodcastIdEditLazyRoute: typeof PodcastsPodcastIdEditLazyRoute
  ScriptsScriptIdEditLazyRoute: typeof ScriptsScriptIdEditLazyRoute
  PodcastsPodcastIdEpisodesEpisodeIdLazyRoute: typeof PodcastsPodcastIdEpisodesEpisodeIdLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podcasts/': {
      id: '/podcasts/'
      path: '/podcasts'
      fullPath: '/podcasts/'
      preLoaderRoute: typeof PodcastsIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scripts/': {
      id: '/scripts/'
      path: '/scripts'
      fullPath: '/scripts/'
      preLoaderRoute: typeof ScriptsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$userId': {
      id: '/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof UsersUserIdLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scripts/new': {
      id: '/scripts/new'
      path: '/scripts/new'
      fullPath: '/scripts/new'
      preLoaderRoute: typeof ScriptsNewLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scripts/$scriptId': {
      id: '/scripts/$scriptId'
      path: '/scripts/$scriptId'
      fullPath: '/scripts/$scriptId'
      preLoaderRoute: typeof ScriptsScriptIdLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podcasts/new': {
      id: '/podcasts/new'
      path: '/podcasts/new'
      fullPath: '/podcasts/new'
      preLoaderRoute: typeof PodcastsNewLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podcasts/$podcastId': {
      id: '/podcasts/$podcastId'
      path: '/podcasts/$podcastId'
      fullPath: '/podcasts/$podcastId'
      preLoaderRoute: typeof PodcastsPodcastIdLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scripts/$scriptId_/edit': {
      id: '/scripts/$scriptId_/edit'
      path: '/scripts/$scriptId/edit'
      fullPath: '/scripts/$scriptId/edit'
      preLoaderRoute: typeof ScriptsScriptIdEditLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podcasts/$podcastId_/edit': {
      id: '/podcasts/$podcastId_/edit'
      path: '/podcasts/$podcastId/edit'
      fullPath: '/podcasts/$podcastId/edit'
      preLoaderRoute: typeof PodcastsPodcastIdEditLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podcasts/$podcastId_/episodes/$episodeId': {
      id: '/podcasts/$podcastId_/episodes/$episodeId'
      path: '/podcasts/$podcastId/episodes/$episodeId'
      fullPath: '/podcasts/$podcastId/episodes/$episodeId'
      preLoaderRoute: typeof PodcastsPodcastIdEpisodesEpisodeIdLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  SigninLazyRoute: SigninLazyRoute,
  PodcastsPodcastIdLazyRoute: PodcastsPodcastIdLazyRoute,
  PodcastsNewLazyRoute: PodcastsNewLazyRoute,
  ScriptsScriptIdLazyRoute: ScriptsScriptIdLazyRoute,
  ScriptsNewLazyRoute: ScriptsNewLazyRoute,
  UsersUserIdLazyRoute: UsersUserIdLazyRoute,
  ScriptsIndexRoute: ScriptsIndexRoute,
  PodcastsIndexLazyRoute: PodcastsIndexLazyRoute,
  PodcastsPodcastIdEditLazyRoute: PodcastsPodcastIdEditLazyRoute,
  ScriptsScriptIdEditLazyRoute: ScriptsScriptIdEditLazyRoute,
  PodcastsPodcastIdEpisodesEpisodeIdLazyRoute:
    PodcastsPodcastIdEpisodesEpisodeIdLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
