//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "episodes")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub title: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub audio_url: Option<String>,
    pub user_id: Option<Uuid>,
    pub podcast_id: Uuid,
    #[sea_orm(column_type = "Text", nullable)]
    pub srt_url: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "JsonBinary")]
    pub sections: Json,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub duration_sec: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::podcasts::Entity",
        from = "Column::PodcastId",
        to = "super::podcasts::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Podcasts,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::podcasts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Podcasts.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
