//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

pub use super::corners::Entity as Corners;
pub use super::episodes::Entity as Episodes;
pub use super::mails::Entity as Mails;
pub use super::podcasts::Entity as Podcasts;
pub use super::scripts::Entity as Scripts;
pub use super::tasks::Entity as Tasks;
pub use super::users::Entity as Users;
