/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ScriptsIndexImport } from './routes/scripts/index'

// Create Virtual Routes

const TasksLazyImport = createFileRoute('/tasks')()
const SigninLazyImport = createFileRoute('/signin')()
const IndexLazyImport = createFileRoute('/')()
const UsersUserIdLazyImport = createFileRoute('/users/$userId')()
const ScriptsNewLazyImport = createFileRoute('/scripts/new')()
const ScriptsScriptIdLazyImport = createFileRoute('/scripts/$scriptId')()
const PodcastsNewLazyImport = createFileRoute('/podcasts/new')()
const PodcastsPodcastIdLazyImport = createFileRoute('/podcasts/$podcastId')()
const EpisodesEpisodeIdLazyImport = createFileRoute('/episodes/$episodeId')()
const EpisodesEpisodeIdEditLazyImport = createFileRoute(
  '/episodes/$episodeId/edit',
)()

// Create/Update Routes

const TasksLazyRoute = TasksLazyImport.update({
  path: '/tasks',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/tasks.lazy').then((d) => d.Route))

const SigninLazyRoute = SigninLazyImport.update({
  path: '/signin',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/signin.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const ScriptsIndexRoute = ScriptsIndexImport.update({
  path: '/scripts/',
  getParentRoute: () => rootRoute,
} as any)

const UsersUserIdLazyRoute = UsersUserIdLazyImport.update({
  path: '/users/$userId',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/users/$userId.lazy').then((d) => d.Route))

const ScriptsNewLazyRoute = ScriptsNewLazyImport.update({
  path: '/scripts/new',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/scripts/new.lazy').then((d) => d.Route))

const ScriptsScriptIdLazyRoute = ScriptsScriptIdLazyImport.update({
  path: '/scripts/$scriptId',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/scripts/$scriptId.lazy').then((d) => d.Route),
)

const PodcastsNewLazyRoute = PodcastsNewLazyImport.update({
  path: '/podcasts/new',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/podcasts/new.lazy').then((d) => d.Route))

const PodcastsPodcastIdLazyRoute = PodcastsPodcastIdLazyImport.update({
  path: '/podcasts/$podcastId',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/podcasts/$podcastId.lazy').then((d) => d.Route),
)

const EpisodesEpisodeIdLazyRoute = EpisodesEpisodeIdLazyImport.update({
  path: '/episodes/$episodeId',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/episodes/$episodeId.lazy').then((d) => d.Route),
)

const EpisodesEpisodeIdEditLazyRoute = EpisodesEpisodeIdEditLazyImport.update({
  path: '/episodes/$episodeId/edit',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/episodes/$episodeId_/edit.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninLazyImport
      parentRoute: typeof rootRoute
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksLazyImport
      parentRoute: typeof rootRoute
    }
    '/episodes/$episodeId': {
      id: '/episodes/$episodeId'
      path: '/episodes/$episodeId'
      fullPath: '/episodes/$episodeId'
      preLoaderRoute: typeof EpisodesEpisodeIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/podcasts/$podcastId': {
      id: '/podcasts/$podcastId'
      path: '/podcasts/$podcastId'
      fullPath: '/podcasts/$podcastId'
      preLoaderRoute: typeof PodcastsPodcastIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/podcasts/new': {
      id: '/podcasts/new'
      path: '/podcasts/new'
      fullPath: '/podcasts/new'
      preLoaderRoute: typeof PodcastsNewLazyImport
      parentRoute: typeof rootRoute
    }
    '/scripts/$scriptId': {
      id: '/scripts/$scriptId'
      path: '/scripts/$scriptId'
      fullPath: '/scripts/$scriptId'
      preLoaderRoute: typeof ScriptsScriptIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/scripts/new': {
      id: '/scripts/new'
      path: '/scripts/new'
      fullPath: '/scripts/new'
      preLoaderRoute: typeof ScriptsNewLazyImport
      parentRoute: typeof rootRoute
    }
    '/users/$userId': {
      id: '/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof UsersUserIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/scripts/': {
      id: '/scripts/'
      path: '/scripts'
      fullPath: '/scripts'
      preLoaderRoute: typeof ScriptsIndexImport
      parentRoute: typeof rootRoute
    }
    '/episodes/$episodeId/edit': {
      id: '/episodes/$episodeId/edit'
      path: '/episodes/$episodeId/edit'
      fullPath: '/episodes/$episodeId/edit'
      preLoaderRoute: typeof EpisodesEpisodeIdEditLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  SigninLazyRoute,
  TasksLazyRoute,
  EpisodesEpisodeIdLazyRoute,
  PodcastsPodcastIdLazyRoute,
  PodcastsNewLazyRoute,
  ScriptsScriptIdLazyRoute,
  ScriptsNewLazyRoute,
  UsersUserIdLazyRoute,
  ScriptsIndexRoute,
  EpisodesEpisodeIdEditLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/signin",
        "/tasks",
        "/episodes/$episodeId",
        "/podcasts/$podcastId",
        "/podcasts/new",
        "/scripts/$scriptId",
        "/scripts/new",
        "/users/$userId",
        "/scripts/",
        "/episodes/$episodeId/edit"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/signin": {
      "filePath": "signin.lazy.tsx"
    },
    "/tasks": {
      "filePath": "tasks.lazy.tsx"
    },
    "/episodes/$episodeId": {
      "filePath": "episodes/$episodeId.lazy.tsx"
    },
    "/podcasts/$podcastId": {
      "filePath": "podcasts/$podcastId.lazy.tsx"
    },
    "/podcasts/new": {
      "filePath": "podcasts/new.lazy.tsx"
    },
    "/scripts/$scriptId": {
      "filePath": "scripts/$scriptId.lazy.tsx"
    },
    "/scripts/new": {
      "filePath": "scripts/new.lazy.tsx"
    },
    "/users/$userId": {
      "filePath": "users/$userId.lazy.tsx"
    },
    "/scripts/": {
      "filePath": "scripts/index.tsx"
    },
    "/episodes/$episodeId/edit": {
      "filePath": "episodes/$episodeId_/edit.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
