/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const TasksLazyImport = createFileRoute('/tasks')()
const SigninLazyImport = createFileRoute('/signin')()
const IndexLazyImport = createFileRoute('/')()
const UsersUserIdLazyImport = createFileRoute('/users/$userId')()
const PodcastsNewLazyImport = createFileRoute('/podcasts/new')()
const PodcastsPodcastIdLazyImport = createFileRoute('/podcasts/$podcastId')()
const EpisodesEpisodeIdLazyImport = createFileRoute('/episodes/$episodeId')()
const PodcastsPodcastIdNewLazyImport = createFileRoute(
  '/podcasts/$podcastId/new',
)()

// Create/Update Routes

const TasksLazyRoute = TasksLazyImport.update({
  path: '/tasks',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/tasks.lazy').then((d) => d.Route))

const SigninLazyRoute = SigninLazyImport.update({
  path: '/signin',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/signin.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const UsersUserIdLazyRoute = UsersUserIdLazyImport.update({
  path: '/users/$userId',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/users/$userId.lazy').then((d) => d.Route))

const PodcastsNewLazyRoute = PodcastsNewLazyImport.update({
  path: '/podcasts/new',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/podcasts/new.lazy').then((d) => d.Route))

const PodcastsPodcastIdLazyRoute = PodcastsPodcastIdLazyImport.update({
  path: '/podcasts/$podcastId',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/podcasts/$podcastId.lazy').then((d) => d.Route),
)

const EpisodesEpisodeIdLazyRoute = EpisodesEpisodeIdLazyImport.update({
  path: '/episodes/$episodeId',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/episodes/$episodeId.lazy').then((d) => d.Route),
)

const PodcastsPodcastIdNewLazyRoute = PodcastsPodcastIdNewLazyImport.update({
  path: '/podcasts/$podcastId/new',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/podcasts/$podcastId_/new.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninLazyImport
      parentRoute: typeof rootRoute
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksLazyImport
      parentRoute: typeof rootRoute
    }
    '/episodes/$episodeId': {
      id: '/episodes/$episodeId'
      path: '/episodes/$episodeId'
      fullPath: '/episodes/$episodeId'
      preLoaderRoute: typeof EpisodesEpisodeIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/podcasts/$podcastId': {
      id: '/podcasts/$podcastId'
      path: '/podcasts/$podcastId'
      fullPath: '/podcasts/$podcastId'
      preLoaderRoute: typeof PodcastsPodcastIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/podcasts/new': {
      id: '/podcasts/new'
      path: '/podcasts/new'
      fullPath: '/podcasts/new'
      preLoaderRoute: typeof PodcastsNewLazyImport
      parentRoute: typeof rootRoute
    }
    '/users/$userId': {
      id: '/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof UsersUserIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/podcasts/$podcastId/new': {
      id: '/podcasts/$podcastId/new'
      path: '/podcasts/$podcastId/new'
      fullPath: '/podcasts/$podcastId/new'
      preLoaderRoute: typeof PodcastsPodcastIdNewLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  SigninLazyRoute,
  TasksLazyRoute,
  EpisodesEpisodeIdLazyRoute,
  PodcastsPodcastIdLazyRoute,
  PodcastsNewLazyRoute,
  UsersUserIdLazyRoute,
  PodcastsPodcastIdNewLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/signin",
        "/tasks",
        "/episodes/$episodeId",
        "/podcasts/$podcastId",
        "/podcasts/new",
        "/users/$userId",
        "/podcasts/$podcastId/new"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/signin": {
      "filePath": "signin.lazy.tsx"
    },
    "/tasks": {
      "filePath": "tasks.lazy.tsx"
    },
    "/episodes/$episodeId": {
      "filePath": "episodes/$episodeId.lazy.tsx"
    },
    "/podcasts/$podcastId": {
      "filePath": "podcasts/$podcastId.lazy.tsx"
    },
    "/podcasts/new": {
      "filePath": "podcasts/new.lazy.tsx"
    },
    "/users/$userId": {
      "filePath": "users/$userId.lazy.tsx"
    },
    "/podcasts/$podcastId/new": {
      "filePath": "podcasts/$podcastId_/new.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
