/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/canvas/edges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["CanvasApi_listEdges"];
        put?: never;
        post: operations["CanvasApi_createEdge"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/canvas/edges/{edgeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["CanvasApi_deleteEdge"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/canvas/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["CanvasApi_query"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/collections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["CollectionApi_list"];
        put?: never;
        post: operations["CollectionApi_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/collections/{collectionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["CollectionApi_read"];
        put: operations["CollectionApi_update"];
        post?: never;
        delete: operations["CollectionApi_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["JobApi_list"];
        put?: never;
        post: operations["JobApi_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/records/{collectionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["RecordApi_list"];
        put?: never;
        post: operations["RecordApi_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/records/{collectionId}/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["RecordApi_generate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/records/{collectionId}/merge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["RecordApi_mergeRecords"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/records/{collectionId}/{recordId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["RecordApi_read"];
        put: operations["RecordApi_update"];
        post?: never;
        delete: operations["RecordApi_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/records/{collectionId}/{recordId}/copy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["RecordApi_copyRecord"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/records/{collectionId}/{recordId}/images/{fieldName}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["RecordApi_getImage"];
        put?: never;
        post: operations["RecordApi_uploadImage"];
        delete: operations["RecordApi_deleteImage"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/records/{collectionId}/{recordId}/split": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["RecordApi_splitRecord"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scripts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ScriptApi_execute"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CanvasQueryRequest: {
            /** @description Starting record ID in "table:id" format */
            record_id: string;
            /** @description Graph traversal depth (default: 1) */
            depth?: number;
            /** @description Filter conditions on record fields */
            conditions?: Record<string, never>;
            /**
             * @description Export format
             * @enum {string}
             */
            format: "json-canvas" | "markdown";
        };
        CanvasQueryResponse: {
            /** @enum {string} */
            format: "json-canvas" | "markdown";
            json_canvas?: components["schemas"]["JsonCanvasResponse"];
            markdown?: string;
        };
        Collection: {
            readonly id: string;
            name: string;
            schema: Record<string, never>;
            readonly created_at: string;
        };
        CopyRecordRequest: {
            /** @description Target collection ID to copy the record to */
            target_collection_id: string;
        };
        CreateEdgeRequest: {
            from: string;
            to: string;
            label: string;
        };
        CreateOrUpdateCollection: {
            name: string;
            schema: Record<string, never>;
        };
        CreateOrUpdateJob: {
            name: string;
            params: Record<string, never>;
        };
        CreateOrUpdateRecord_: {
            data: Record<string, never>;
        };
        Edge: {
            readonly id: string;
            /** @description Source record ID in "table:id" format */
            from: string;
            /** @description Target record ID in "table:id" format */
            to: string;
            /** @description Edge label (e.g. "belongs_to", "related_to") */
            label: string;
            readonly created_at: string;
        };
        ExecuteScriptRequest: {
            /** @enum {string} */
            language: "python3" | "nodejs";
            code: string;
            preload?: string;
            enable_network?: boolean;
        };
        ExecuteScriptResponse: {
            code: number;
            message: "success" | string;
            data: {
                stdout: string;
                error: string;
            };
        };
        GenerateRecordRequest: {
            prompt: string;
        };
        GetImageResponse: {
            /** @description Base64 encoded image data */
            data: string;
            /** @description MIME type */
            content_type: string;
            /** @description File size in bytes */
            size: number;
        };
        ImageField: {
            /** @description File pointer (e.g. "images:/collection_id/record_id/field_name") */
            pointer: string;
            /** @description MIME type (e.g. "image/png", "image/jpeg") */
            content_type: string;
            /** @description File size in bytes */
            size: number;
            /** @description Image URL */
            url: string;
        };
        Job: {
            name: string;
            params: Record<string, never>;
            readonly status: string;
        };
        JsonCanvasEdge: {
            id: string;
            fromNode: string;
            toNode: string;
            label?: string;
        };
        JsonCanvasNode: {
            id: string;
            x: number;
            y: number;
            width: number;
            height: number;
            /** @enum {string} */
            type: "text";
            text: string;
        };
        JsonCanvasResponse: {
            nodes: components["schemas"]["JsonCanvasNode"][];
            edges: components["schemas"]["JsonCanvasEdge"][];
        };
        MergeRecordsRequest: {
            /** @description Record IDs to merge (first one becomes the target) */
            source_record_ids: string[];
            /** @description Target record ID (must be in source_record_ids) */
            target_record_id: string;
            /** @description Field names to add (numeric values will be summed) */
            add_fields?: string[];
            /** @description Whether to delete source records after merge (default: false) */
            delete_sources?: boolean;
        };
        NotFoundError: {
            /** @enum {string} */
            code: "NOT_FOUND";
            message: string;
        };
        Record_: {
            readonly id: string;
            data: Record<string, never>;
            readonly created_at: string | null;
            readonly updated_at: string | null;
        };
        SplitRecordRequest: {
            /** @description Split specifications: each object contains field names and values to subtract */
            splits: Record<string, never>[];
        };
        SplitRecordResponse: {
            /** @description Original record after split (with subtracted values) */
            original: components["schemas"]["Record_"];
            /** @description New records created from splits */
            splits: components["schemas"]["Record_"][];
        };
        UpdateCollection: {
            name: string;
        };
        UploadImageRequest: {
            /** @description Base64 encoded image data */
            data: string;
            /**
             * @description MIME type
             * @enum {string}
             */
            content_type: "image/png" | "image/jpeg" | "image/webp" | "image/gif";
            /** @description Optional filename */
            filename?: string;
        };
        UploadImageResponse: {
            /** @description Saved file pointer */
            pointer: string;
            /** @description Image URL */
            url: string;
        };
        ValidationError: {
            /** @enum {string} */
            code: "VALIDATION_ERROR";
            message: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    CanvasApi_listEdges: {
        parameters: {
            query: {
                record_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Edge"][];
                };
            };
        };
    };
    CanvasApi_createEdge: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEdgeRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Edge"];
                };
            };
        };
    };
    CanvasApi_deleteEdge: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                edgeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description There is no content to send for this request, but the headers may be useful.  */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CanvasApi_query: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CanvasQueryRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CanvasQueryResponse"];
                };
            };
        };
    };
    CollectionApi_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Collection"][];
                };
            };
        };
    };
    CollectionApi_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrUpdateCollection"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Collection"];
                };
            };
        };
    };
    CollectionApi_read: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                collectionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Collection"];
                };
            };
        };
    };
    CollectionApi_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                collectionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCollection"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Collection"];
                };
            };
        };
    };
    CollectionApi_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                collectionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description There is no content to send for this request, but the headers may be useful.  */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    JobApi_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"][];
                };
            };
        };
    };
    JobApi_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrUpdateJob"];
            };
        };
        responses: {
            /** @description There is no content to send for this request, but the headers may be useful.  */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RecordApi_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                collectionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Record_"][];
                };
            };
        };
    };
    RecordApi_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                collectionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrUpdateRecord_"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Record_"];
                };
            };
        };
    };
    RecordApi_generate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                collectionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateRecordRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Record_"];
                };
            };
        };
    };
    RecordApi_mergeRecords: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                collectionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MergeRecordsRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Record_"];
                };
            };
        };
    };
    RecordApi_read: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                collectionId: string;
                recordId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Record_"];
                };
            };
        };
    };
    RecordApi_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                collectionId: string;
                recordId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrUpdateRecord_"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Record_"];
                };
            };
        };
    };
    RecordApi_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                collectionId: string;
                recordId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description There is no content to send for this request, but the headers may be useful.  */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RecordApi_copyRecord: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                collectionId: string;
                recordId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CopyRecordRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Record_"];
                };
            };
        };
    };
    RecordApi_getImage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                collectionId: string;
                recordId: string;
                fieldName: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": unknown;
                };
            };
        };
    };
    RecordApi_uploadImage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                collectionId: string;
                recordId: string;
                fieldName: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UploadImageRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadImageResponse"];
                };
            };
        };
    };
    RecordApi_deleteImage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                collectionId: string;
                recordId: string;
                fieldName: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description There is no content to send for this request, but the headers may be useful.  */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RecordApi_splitRecord: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                collectionId: string;
                recordId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SplitRecordRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SplitRecordResponse"];
                };
            };
        };
    };
    ScriptApi_execute: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExecuteScriptRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExecuteScriptResponse"];
                };
            };
        };
    };
}
