name: CMS Check

on:
  push:
    branches: [main]
    paths:
      - "botcast-cms/cms/**"
  pull_request:
    paths:
      - "botcast-cms/cms/**"

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: botcast-cms/cms

      - name: cargo check
        run: cargo check --workspace
        working-directory: botcast-cms/cms

      - name: cargo test
        run: cargo test --workspace
        working-directory: botcast-cms/cms
