name: Publish on GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Build rustdoc
        run: cd botcast-worker && cargo doc --no-deps --workspace

      - name: Add redirect index
        run: |
          echo '<meta http-equiv="refresh" content="0; url=worker/index.html">' \
            > botcast-worker/target/doc/index.html

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: "botcast-worker/target/doc"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
